### ISSUE TITLE
You messed up all the code.

### ISSUE THREAD

**Issue by PeeMoldy** [aMannus/HolidaysInHyrule#12]
Yeah you left the texture where Dampe's Grave is in Young Link timeline unreplaced with a snow texture, and the guards are missing hands. Maybe you should fix all this stuff.

![sohvmd803holidaypackmirroredgraveyardunsnowedgroundpatch](https://github.com/aMannus/HolidaysInHyrule/assets/152383944/c18445f7-9f92-49af-ae44-ff289b9c8b29)
![sohvmd803holidaypackmirroredgraveyardunsnowedgroundpatchii](https://github.com/aMannus/HolidaysInHyrule/assets/152383944/35c33d07-29af-4a23-808c-f170d7a4ae95)
![sohvmd803holidaypackmirroredhchandlesssoldier](https://github.com/aMannus/HolidaysInHyrule/assets/152383944/a35e8f36-743d-4fd8-b7a3-3335252643d2)

**Comment by aMannusAtePoop** [comment]
You can't stop me. I have infinite lives. You can ban and ban and ban, and you can never get rid of me. I am fucking invincible, you filthy conspirator. https://www.youtube.com/watch?v=JmGMzyajA2U

**Comment by aMannusAtePoop** [comment]
Sheepytina is a man, and there are only 2 genders. Just admit the truth Marxist.
